<a href="https://colab.research.google.com/github/enjoy301/deep-learning-playground/blob/main/DeepLearningWithPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서 다루기

In [3]:
import torch

print(torch.tensor([[1,2], [3,4]]))
print(torch.tensor([[1,2], [3,4]], device="cuda:0"))
print(torch.tensor([[1,2], [3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [7]:
temp = torch.tensor([
    [1, 2],
    [3, 4],
])

print(temp.shape)

# 4x1 행렬로 변형
print(temp.view(4, 1))

# 1차원 벡터로 변형
print(temp.view(-1))

# 1x? 행렬로 변형
print(temp.view(1, -1))

# ?x1 행렬로 변형
print(temp.view(-1, 1))

torch.Size([2, 2])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
